export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";
export const CAN_SET_INGREDIENTS = "CAN_SET_INGREDIENTS";
export const SET_BUILDING_BURGER = "SET_BUILDING_BURGER";

export const BURGER_PURCHASE_INIT = "BURGER_PURCHASE_INIT";
export const BURGER_PURCHASE_SUCCESS = "BURGER_PURCHASE_SUCCESS";
export const BURGER_PURCHASE_FAILED = "BURGER_PURCHASE_FAILED";

export const FETCH_ORDER_START = "FETCH_ORDER_START";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_FAILED = "FETCH_ORDER_FAILED";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
// export const AUTH_SIGNIN = "AUTH_SIGNIN";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
